// <autogenerated />
using System.Globalization;

namespace ClassesCalendar
{
    public partial class ClassesCalendarComponent
    {
        private DateTime currentDate = DateTime.Now;
        private int currentMonth => currentDate.Month;
        private int currentYear => currentDate.Year;
        private string currentMonthName => CultureInfo.CurrentCulture.DateTimeFormat.GetMonthName(currentMonth);
        private int daysInMonth => DateTime.DaysInMonth(currentYear, currentMonth);
        private string[] daysOfWeek = new[] { "Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat" };

        private void PrevMonth()
        {
            currentDate = currentDate.AddMonths(-1);
        }

        private void NextMonth()
        {
            currentDate = currentDate.AddMonths(1);
        }
    }
}